apiVersion: apps/v1
kind: Deployment
metadata:
  name: baro-order
  labels:
    app: baro-order
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: baro-order
  template:
    metadata:
      labels:
        app: baro-order
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: baro-order
          image: 299369991605.dkr.ecr.ap-northeast-2.amazonaws.com/baro-prod/baro-order:sha-df9a50e
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: http
          envFrom:
            - configMapRef:
                name: baro-order-config
            - configMapRef:
                name: infra-endpoints-config
          env:
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONFIG_IMPORT_CHECK_ENABLED
              value: "false"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: baro-order-secrets
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: baro-order-secrets
                  key: AWS_SECRET_KEY
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: baro-order-secrets
                  key: AWS_S3_BUCKET_NAME
