services:
  redis:
    volumes:
      - redis-data:/data
  kafka:
    volumes:
      - kafka-data:/var/lib/kafka/data
  elasticsearch:
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
