x-s3-dummy: &s3_dummy
  - s3_dummy:/mnt/s3

services:
  redis:
    volumes: *s3_dummy
  mysql:
    volumes: *s3_dummy
  kafka:
    volumes: *s3_dummy
  elasticsearch:
    volumes: *s3_dummy
  eureka:
    volumes: *s3_dummy
  config:
    volumes: *s3_dummy
  gateway:
    volumes: *s3_dummy
  opa:
    volumes: *s3_dummy
  opa-bundle:
    volumes: *s3_dummy
  baro-auth:
    volumes: *s3_dummy
  baro-ai:
    volumes: *s3_dummy
  baro-buyer:
    volumes: *s3_dummy
  baro-seller:
    volumes: *s3_dummy
  baro-order:
    volumes: *s3_dummy
  baro-payment:
    volumes: *s3_dummy
  baro-support:
    volumes: *s3_dummy

volumes:
  s3_dummy: {}
