apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: baro-prod

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

labels:
  - includeSelectors: false  # selector는 immutable이므로 false로 설정
    includeTemplates: true
    pairs:
      app: baro-ai
      component: app

images:
  - name: ghcr.io/do-develop-space/baro-ai
    newTag: latest

